/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as RoleRoleIdRouteImport } from './routes/role.$roleId'
import { Route as ToolsYoutubeRouteImport } from './routes/tools/youtube'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoleIdRoute = RoleRoleIdRouteImport.update({
  id: '/role/$roleId',
  path: '/role/$roleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsYoutubeRoute = ToolsYoutubeRouteImport.update({
  id: '/tools/youtube',
  path: '/tools/youtube',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claims': typeof ClaimsRoute
  '/scoreboard': typeof ScoreboardRoute
  '/role/$roleId': typeof RoleRoleIdRoute
  '/tools/youtube': typeof ToolsYoutubeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claims': typeof ClaimsRoute
  '/scoreboard': typeof ScoreboardRoute
  '/role/$roleId': typeof RoleRoleIdRoute
  '/tools/youtube': typeof ToolsYoutubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claims': typeof ClaimsRoute
  '/scoreboard': typeof ScoreboardRoute
  '/role/$roleId': typeof RoleRoleIdRoute
  '/tools/youtube': typeof ToolsYoutubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/claims'
    | '/scoreboard'
    | '/role/$roleId'
    | '/tools/youtube'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/claims'
    | '/scoreboard'
    | '/role/$roleId'
    | '/tools/youtube'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/claims'
    | '/scoreboard'
    | '/role/$roleId'
    | '/tools/youtube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClaimsRoute: typeof ClaimsRoute
  ScoreboardRoute: typeof ScoreboardRoute
  RoleRoleIdRoute: typeof RoleRoleIdRoute
  ToolsYoutubeRoute: typeof ToolsYoutubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role/$roleId': {
      id: '/role/$roleId'
      path: '/role/$roleId'
      fullPath: '/role/$roleId'
      preLoaderRoute: typeof RoleRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/youtube': {
      id: '/tools/youtube'
      path: '/tools/youtube'
      fullPath: '/tools/youtube'
      preLoaderRoute: typeof ToolsYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClaimsRoute: ClaimsRoute,
  ScoreboardRoute: ScoreboardRoute,
  RoleRoleIdRoute: RoleRoleIdRoute,
  ToolsYoutubeRoute: ToolsYoutubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
